### PR TITLE
wrap fields + values in a label

### PR DESCRIPTION
**Pull request by BrianHicks**
this fixes a bunch of a11y violations found by axe in the example!

### CODE REVIEW

**Comment by avh4** [comment]
This change seems to not be valid HTML, according to https://www.w3.org/TR/html53/tabular-data.html#the-tr-element  I'd be hesitant to make this change to appease axe when it seems to violate the HTML spec.  Did you have any references that this is a recommended approach for accessible web pages?

**Comment by BrianHicks** [comment]
mmm, sorry! I didn't realize the spec interacted like this.

The other option is to set an ID on the input and then a `<label for="the-id">`. That would probably work well but I am concerned what would happen if there were two IDs on the page because of, say, a list of debug controls

**Comment by avh4** [comment]
hmm, maybe the input could be wrapped in an invisible label?  Or maybe the layout could be reworked to use `display: table-row` etc instead of actual table/tr/td elements?  Or is it possible to use css grid with `<div> <label> text <input/> </label> ... </div>` and put nested elements into different cells?

**Comment by avh4** [comment]
@BrianHicks did this actually fix the aXe checks?  If so, I think I'll merge this for now, as making correct labels is going to require either making the internal data structures messier, or changing the public API.

**Comment by BrianHicks** [comment]
I think it fixed them but it’s been a while. The display fix might be better here.

But also, since this is a tree, I wonder if it’d be reasonable to create unique ids

**Comment by avh4** [comment]
unique ids wouldn't solve everything, since in out styleguide, we have multiple controls ending up on the same page, so the caller would still have to provide a seed id for each control.

Ah right, I forgot about the display:table-row trick... I'll give that a try tomorrow

**Pull request merged**
