### PR TITLE
Adds longString Control

### PR DESCRIPTION
**Pull request by tesk9**
Adds a text area control, to support multi-line text. I called it longString -- maybe multilineString would be better?

Screen Shot 2019-09-10 at 12 22 16 PM

### CODE REVIEW

**Comment by avh4** [comment]
I was thinking `textarea` might make sense, since that's a term most Elm devs would understand to mean the same thing (whereas `input` or `field` doesn't really make sense for the simpler string input since they're pretty vague terms).   But yeah, `multilineString` seems to fit best with the existing `string` function, though maybe it wouldn't be as obvious what to search for if you didn't know the name already?

`longString` also seems fine.   Let me know if you want to change to one of the other options, or if you want me to merge this as-is.

**Comment by tesk9** [comment]
Hmm, I don't feel strongly! All the options seem good. Do you have a preference at all? I'm very happy to change it to `textarea` or `multilineString`

**Comment by avh4** [comment]
Ah, reading through the API again, I remember the naming scheme I was aiming for:  have the data type be the primary focus, and alternate UI widgets be secondary.

Based on that, let's go with `stringTextarea`  if that sounds okay.

**Comment by tesk9** [comment]
Love it! change made

**Pull request merged**
